dist: bionic
language: python
python:
  - "3.7"
install:
  - pip install -e .
  - pip install pytest-cov
script:
  - pytest --cov=aes_sha1prng --cov-report=term-missing --disable-pytest-warnings test
after_success:
  - pip install codecov
  - codecov
